#!/usr/bin/env bash
# Configures Nginx for redirection

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
