#!/usr/bin/env bash
# Configures Nginx to add a custom HTTP header

# Update packages
sudo apt-get update
sudo apt-get -y install nginx

# Create a basic HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx with custom header
sudo sed -i "/server_name _;/a \    add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
