#!/usr/bin/env bash
# Displays listening ports and associated programs

# Print header for TCP connections
echo "Active Internet connections (only servers)"

# Get active TCP connections and print formatted output
tcp_conns=$(sudo netstat -lntp 2>/dev/null | awk 'NR>2 {printf "%s %-5s %-5s %-16s %-16s %-11s %-18s\n", $1, $2, $3, $4, $5, $6, $7}' ORS='')
echo "$tcp_conns"
echo ""

# Print header for UDP connections 
echo "Active UNIX domain sockets (only servers)"

# Get active UDP connections and print formatted output
unix_conns=$(sudo netstat -lxunp 2>/dev/null | awk 'NR<3 {next} {printf "%s %-6s %-5s %-15s %-6s %-6s %-20s %-19s\n", $1, $2, $3, $4, $5, $6, $7, $8}' ORS='')
echo "$unix_conns"
echo ""

# Print header for UDP connections
echo "UDP ports"

# Get active UDP connections and print formatted output
udp_conns=$(sudo netstat -lunp 2>/dev/null | awk 'NR>2 {printf "%s %-5s %-5s %-16s %-16s %-11s %-18s\n", $1, $2, $3, $4, $5, $6, $7}' ORS='')
echo "$udp_conns"
