#!/usr/bin/env bash
# This script displays the username, user ID, and home directory path for each user in the /etc/passwd file

while IFS=: read -r username password uid gid info home shell
do
    echo "$username:$uid:$home"
done < /etc/passwd
