#!/usr/bin/env bash
# Fix Apache to serve "Hello Holberton" page
apt-get update
apt-get install -y apache2
echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2/apache2.conf
service apache2 start
